import React from 'react';
import {
  BookOpen, Globe, Smartphone, BarChart3, Layout, Terminal,
  GraduationCap, Coffee, Zap, Rocket,
  Users, Clock, Award
} from 'lucide-react';

export const TUTORIAL_CATEGORIES = [
  { id: 'all', name: 'All Tutorials', icon: React.createElement(BookOpen, { className: 'w-5 h-5' }), count: 156, color: 'blue' },
  { id: 'web', name: 'Web Development', icon: React.createElement(Globe, { className: 'w-5 h-5' }), count: 45, color: 'green' },
  { id: 'mobile', name: 'Mobile Development', icon: React.createElement(Smartphone, { className: 'w-5 h-5' }), count: 28, color: 'purple' },
  { id: 'data', name: 'Data Science', icon: React.createElement(BarChart3, { className: 'w-5 h-5' }), count: 32, color: 'orange' },
  { id: 'design', name: 'UI/UX Design', icon: React.createElement(Layout, { className: 'w-5 h-5' }), count: 24, color: 'pink' },
  { id: 'backend', name: 'Backend', icon: React.createElement(Terminal, { className: 'w-5 h-5' }), count: 27, color: 'indigo' },
];

export const TUTORIAL_LEVELS = [
  { id: 'all', name: 'All Levels', icon: React.createElement(GraduationCap, { className: 'w-4 h-4' }) },
  { id: 'beginner', name: 'Beginner', icon: React.createElement(Coffee, { className: 'w-4 h-4' }) },
  { id: 'intermediate', name: 'Intermediate', icon: React.createElement(Zap, { className: 'w-4 h-4' }) },
  { id: 'advanced', name: 'Advanced', icon: React.createElement(Rocket, { className: 'w-4 h-4' }) },
];

export const TUTORIALS = [
  {
    id: 1,
    title: 'Complete JavaScript Mastery',
    description: 'Master JavaScript from basics to advanced concepts with real-world projects and exercises.',
    category: 'web',
    level: 'beginner',
    duration: '25 hours',
    students: '45.2K',
    rating: 4.8,
    instructor: 'John Doe',
    instructorRole: 'Senior Developer',
    instructorAvatar: '👨‍💻',
    lessons: 156,
    projects: 12,
    quizzes: 24,
    language: 'English',
    lastUpdated: '2024',
    certificate: true,
    featured: true,
    trending: true,
    tags: ['JavaScript', 'ES6', 'Async', 'DOM'],
    image: '🚀',
    color: 'from-yellow-500 to-orange-500',
    progress: 65,
    bookmarked: false,
  },
  {
    id: 2,
    title: 'React - The Complete Guide',
    description: 'Learn React from scratch with hooks, context, Redux, and build modern web applications.',
    category: 'web',
    level: 'intermediate',
    duration: '30 hours',
    students: '38.9K',
    rating: 4.9,
    instructor: 'Jane Smith',
    instructorRole: 'React Expert',
    instructorAvatar: '👩‍💻',
    lessons: 189,
    projects: 15,
    quizzes: 32,
    language: 'English',
    lastUpdated: '2024',
    certificate: true,
    featured: true,
    trending: true,
    tags: ['React', 'Hooks', 'Redux', 'Next.js'],
    image: '⚛️',
    color: 'from-cyan-500 to-blue-500',
    progress: 30,
    bookmarked: true,
  },
  {
    id: 3,
    title: 'Python for Data Science',
    description: 'Learn Python programming and its applications in data science, machine learning, and AI.',
    category: 'data',
    level: 'intermediate',
    duration: '20 hours',
    students: '32.5K',
    rating: 4.7,
    instructor: 'Mike Johnson',
    instructorRole: 'Data Scientist',
    instructorAvatar: '👨‍🔬',
    lessons: 134,
    projects: 8,
    quizzes: 18,
    language: 'English',
    lastUpdated: '2023',
    certificate: true,
    featured: false,
    trending: true,
    tags: ['Python', 'Pandas', 'NumPy', 'Matplotlib'],
    image: '🐍',
    color: 'from-green-500 to-emerald-500',
    progress: 0,
    bookmarked: false,
  },
  {
    id: 4,
    title: 'Flutter & Dart Masterclass',
    description: 'Build beautiful native iOS and Android apps with Flutter from scratch.',
    category: 'mobile',
    level: 'beginner',
    duration: '35 hours',
    students: '28.7K',
    rating: 4.8,
    instructor: 'Sarah Wilson',
    instructorRole: 'Mobile Dev',
    instructorAvatar: '👩‍🎨',
    lessons: 210,
    projects: 18,
    quizzes: 28,
    language: 'English',
    lastUpdated: '2024',
    certificate: true,
    featured: true,
    trending: false,
    tags: ['Flutter', 'Dart', 'iOS', 'Android'],
    image: '📱',
    color: 'from-blue-500 to-indigo-500',
    progress: 45,
    bookmarked: false,
  },
  {
    id: 5,
    title: 'Advanced CSS & Sass',
    description: 'Master CSS with Flexbox, Grid, animations, and modern responsive design techniques.',
    category: 'design',
    level: 'intermediate',
    duration: '15 hours',
    students: '42.1K',
    rating: 4.9,
    instructor: 'Alex Chen',
    instructorRole: 'UI Designer',
    instructorAvatar: '👨‍🎨',
    lessons: 98,
    projects: 10,
    quizzes: 15,
    language: 'English',
    lastUpdated: '2024',
    certificate: true,
    featured: false,
    trending: true,
    tags: ['CSS3', 'Sass', 'Flexbox', 'Grid'],
    image: '🎨',
    color: 'from-pink-500 to-rose-500',
    progress: 80,
    bookmarked: true,
  },
  {
    id: 6,
    title: 'Node.js API Development',
    description: 'Build scalable REST APIs and GraphQL servers with Node.js and Express.',
    category: 'backend',
    level: 'advanced',
    duration: '18 hours',
    students: '23.4K',
    rating: 4.7,
    instructor: 'David Brown',
    instructorRole: 'Backend Architect',
    instructorAvatar: '👨‍💻',
    lessons: 112,
    projects: 9,
    quizzes: 20,
    language: 'English',
    lastUpdated: '2023',
    certificate: true,
    featured: true,
    trending: false,
    tags: ['Node.js', 'Express', 'MongoDB', 'REST'],
    image: '🖥️',
    color: 'from-green-600 to-emerald-600',
    progress: 15,
    bookmarked: false,
  },
  {
    id: 7,
    title: 'Machine Learning A-Z',
    description: 'Learn machine learning algorithms and build AI models with Python and scikit-learn.',
    category: 'data',
    level: 'advanced',
    duration: '40 hours',
    students: '19.8K',
    rating: 4.8,
    instructor: 'Dr. Emily White',
    instructorRole: 'ML Researcher',
    instructorAvatar: '👩‍🔬',
    lessons: 245,
    projects: 14,
    quizzes: 35,
    language: 'English',
    lastUpdated: '2024',
    certificate: true,
    featured: false,
    trending: true,
    tags: ['ML', 'Python', 'Scikit-learn', 'TensorFlow'],
    image: '🤖',
    color: 'from-purple-500 to-indigo-500',
    progress: 0,
    bookmarked: false,
  },
  {
    id: 8,
    title: 'iOS Development with Swift',
    description: 'Build iOS apps from scratch using Swift and SwiftUI with Apple\'s latest frameworks.',
    category: 'mobile',
    level: 'intermediate',
    duration: '32 hours',
    students: '21.3K',
    rating: 4.8,
    instructor: 'Chris Parker',
    instructorRole: 'iOS Developer',
    instructorAvatar: '👨‍💻',
    lessons: 178,
    projects: 13,
    quizzes: 22,
    language: 'English',
    lastUpdated: '2024',
    certificate: true,
    featured: true,
    trending: false,
    tags: ['Swift', 'iOS', 'SwiftUI', 'Xcode'],
    image: '🍎',
    color: 'from-gray-700 to-gray-900',
    progress: 25,
    bookmarked: true,
  },
  {
    id: 9,
    title: 'Vue.js - The Complete Guide',
    description: 'Master Vue.js from basics to advanced with composition API, Vuex, and router.',
    category: 'web',
    level: 'intermediate',
    duration: '22 hours',
    students: '27.6K',
    rating: 4.7,
    instructor: 'Emma Davis',
    instructorRole: 'Frontend Lead',
    instructorAvatar: '👩‍💻',
    lessons: 145,
    projects: 11,
    quizzes: 19,
    language: 'English',
    lastUpdated: '2023',
    certificate: true,
    featured: false,
    trending: true,
    tags: ['Vue.js', 'Vuex', 'Router', 'Composition API'],
    image: '🟢',
    color: 'from-green-400 to-emerald-500',
    progress: 0,
    bookmarked: false,
  },
];

export const TUTORIAL_STATS = [
  { icon: React.createElement(BookOpen, { className: 'w-6 h-6' }), label: 'Tutorials', value: '150+', color: 'from-blue-500 to-cyan-500', bg: 'from-blue-50 to-cyan-50' },
  { icon: React.createElement(Users, { className: 'w-6 h-6' }), label: 'Students', value: '250K+', color: 'from-green-500 to-emerald-500', bg: 'from-green-50 to-emerald-50' },
  { icon: React.createElement(Clock, { className: 'w-6 h-6' }), label: 'Hours', value: '500+', color: 'from-purple-500 to-pink-500', bg: 'from-purple-50 to-pink-50' },
  { icon: React.createElement(Award, { className: 'w-6 h-6' }), label: 'Certificates', value: '25+', color: 'from-amber-500 to-orange-500', bg: 'from-amber-50 to-orange-50' },
];

export const TUTORIAL_HERO = {
  gradient: 'from-blue-600 via-purple-600 to-pink-600',
  badgeText: '500+ hours of content',
  titleLine1: 'Learn from the best',
  titleLine2: 'tutorials & courses',
  description: 'Access 150+ expert-led tutorials, hands-on projects, and earn certificates to advance your career.',
  primaryCtaLabel: 'Start Learning Free',
  primaryCtaColor: 'text-blue-600',
  secondaryCtaLabel: 'Browse All Tutorials',
  maxWidth: 'max-w-4xl',
};

export const TUTORIAL_SEARCH_PLACEHOLDER = 'Search tutorials by title, topic, or tags...';

export const TUTORIAL_LEVEL_FILTER_LABEL = 'Level';

export const NEWSLETTER = {
  badgeText: 'Never miss an update',
  title: 'Stay updated with new tutorials',
  description: 'Get notified when we publish new tutorials, courses, and learning resources.',
  inputPlaceholder: 'Enter your email',
  submitLabel: 'Subscribe',
  note: 'Join 50,000+ developers who get our newsletter',
};

export const FEATURED_SECTION_TITLE = 'Featured Tutorials';
export const TRENDING_SECTION_TITLE = 'Trending Now';
export const VIEW_ALL_LABEL = 'View All';

export const TUTORIAL_GRID_SORT_OPTIONS = ['Most Popular', 'Newest First', 'Highest Rated', 'Most Duration'];
export const TUTORIAL_GRID_EMPTY_TITLE = 'No tutorials found';
export const TUTORIAL_GRID_EMPTY_DESC = 'We couldn\'t find any tutorials matching your criteria. Try adjusting your filters.';
export const TUTORIAL_GRID_LOAD_MORE = 'Load More Tutorials';
export const TUTORIAL_GRID_CLEAR_FILTERS = 'Clear All Filters';

export const TUTORIAL_CARD_TRENDING_LABEL = 'Trending';
export const TUTORIAL_CARD_CERTIFICATE_LABEL = 'Certificate';
export const TUTORIAL_CARD_RESOURCES_LABEL = 'Resources included';
export const TUTORIAL_CARD_SHOW_MORE = 'Show more details';
export const TUTORIAL_CARD_SHOW_LESS = 'Show less';
